### ISSUE TITLE
J2KExtendedCapabilities shall be present when using HTJ2K codestreams

### ISSUE THREAD

**Issue by michaeldsmith** [SMPTE/st2067-21#2]
HTJ2K codestreams include a CAP (extended capabilities) marker that includes information about the HTJ2K codestream that could be useful to a decoder, for example HT cleanup magnitude bound.

![image](https://user-images.githubusercontent.com/37905569/146823783-b3320161-23e2-4d1e-a6ed-8a8b22ff72df.png)

ST422:2019 indicates that J2KExtendedCapabilities item is optional in general.  It should be required for IMF MXF trackfiles that include HTJ2K.    

![image](https://user-images.githubusercontent.com/37905569/146823736-cebbfd75-626a-48f2-9ccf-f24d482214ff.png)

To indicate this, a row could be added to Table 14 with entry:
J2KExtendedCapabilities - Shall be present if ISO/IEC 15544-15 coding is used.

![image](https://user-images.githubusercontent.com/37905569/146825386-49dce470-c5b7-45ee-a6e6-0fe30e079d10.png)

**Comment by Editman3153** [comment]
Issues addressed.  Thank you, Harvey

**Comment by palemieux** [comment]
See https://smpte.sharepoint.com/:u:/s/35pm-doc-mx/ETlxuyKxWNJAl6qeZfz6BRcBwFdUzYg6iBR3I7poIu3w3Q?e=gPpevE
