### ISSUE TITLE
StereoImageTrackFileResourceType constraints incomplete

### ISSUE THREAD

**Issue by jhursty** [SMPTE/st2067-21#5]
There is a required child element of `StereoImageTrackFileResourceType`, `IntrinsicDuration`, which could be in conflict with the same value in the respective `LeftEye` and `RightEye` sub-elements, in the case where the underlying MXF track files do not have equal container duration.

There are also optional elements (`EditRate`, `SourceDuration`, `RepeatCount`) of `StereoImageTrackFileResourceType` which could be in conflict when present, or could be expected (required) by some implementations.

Additional constraints should be considered.

**Comment by palemieux** [comment]
See Annex C at ST 2067-2

**Comment by jhursty** [comment]
I have read it. It does not address the case where `IntrinsicDuration` differs between `LeftEye` and `RightEye`. I will re-post this issue in SMPTE/st2067-2.
